backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "source/uploads" # Folder where uploaded files are saved
public_folder: "uploads" # Folder used in output file

collections:
  - name: "canciones"
    label: "Canciones"
    folder: "source/canciones"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/letra" # This creates folder/letra.txt structure!
    extension: "txt"
    format: "frontmatter"
    fields:
      - {label: "TÃ­tulo", name: "title", widget: "string"}
      - {label: "Artista", name: "artist", widget: "string"}
      - {label: "Tonalidad", name: "key", widget: "string"}
      - {label: "Audio Soprano", name: "audio_soprano", widget: "file", required: false}
      - {label: "Audio Alto", name: "audio_alto", widget: "file", required: false}
      - {label: "Audio Tenor", name: "audio_tenor", widget: "file", required: false}
      - {label: "Audio Solista", name: "audio_solista", widget: "file", required: false}
      - {label: "Letra", name: "body", widget: "text"}
